
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  database: test_transaction
#  username: test
#  password: test
#  host: localhost
#  port: 5432

default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: test
  password: test
  host: localhost

development:
  <<: *default
  database: test_transaction_development

test:
  <<: *default
  database: test_test

production:
  <<: *default
  database: test_production
