
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: test_transaction
  username: test
  password: test
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
